"""
scripts/make_phone_defaults.py - write phone/defaults.js from defaults.py.

The phone app is written in JavaScript so it can run offline on a phone, but
every number it uses (intensities, rep tables, splits, ladder ...) must match
the Python app exactly. Instead of typing the tables twice, this script dumps
them from defaults.py into a JavaScript file. Re-run it whenever defaults.py
or the image override map in exercise_library.py changes:

    python scripts/make_phone_defaults.py
"""
import json
import os
import sys

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_DIR)

import defaults          # noqa: E402
import exercise_library  # noqa: E402

OUTPUT_PATH = os.path.join(PROJECT_DIR, "phone", "defaults.js")


def collect_constants():
    """Returns a dict of every UPPER_CASE value in defaults.py that JSON can hold."""
    constants = {}
    for name in dir(defaults):
        if not name.isupper():
            continue
        value = getattr(defaults, name)
        if isinstance(value, tuple):
            value = list(value)
        try:
            json.dumps(value)
        except TypeError:
            continue
        constants[name] = value
    return constants


def main():
    """Writes phone/defaults.js. Returns nothing."""
    constants = collect_constants()
    lines = [
        "// defaults.js - GENERATED by scripts/make_phone_defaults.py from defaults.py.",
        "// Do not edit by hand; change defaults.py and re-run the script.",
        "\"use strict\";",
        "const DEFAULTS = " + json.dumps(constants, indent=2) + ";",
        "const IMAGE_OVERRIDES = " + json.dumps(exercise_library.SBS_IMAGE_OVERRIDES, indent=2) + ";",
        "if (typeof module !== \"undefined\") {",
        "  module.exports = { DEFAULTS: DEFAULTS, IMAGE_OVERRIDES: IMAGE_OVERRIDES };",
        "} else {",
        "  window.SBS_DEFAULTS = DEFAULTS;",
        "  window.SBS_IMAGE_OVERRIDES = IMAGE_OVERRIDES;",
        "}",
        "",
    ]
    with open(OUTPUT_PATH, "w", encoding="utf-8") as file:
        file.write("\n".join(lines))
    print("Wrote " + OUTPUT_PATH + " with " + str(len(constants)) + " constants")


if __name__ == "__main__":
    main()
