// defaults.js - GENERATED by scripts/make_phone_defaults.py from defaults.py.
// Do not edit by hand; change defaults.py and re-run the script.
"use strict";
const DEFAULTS = {
  "ACCESSORY_SUGGESTIONS": [
    "Face Pull",
    "Lateral Raise",
    "Rear Delt Fly",
    "Barbell Curl",
    "Dumbbell Curl",
    "Hammer Curl",
    "Triceps Pushdown",
    "Skull Crusher",
    "Overhead Triceps Extension",
    "Leg Curl",
    "Leg Extension",
    "Hip Thrust",
    "Back Extension",
    "Glute Ham Raise",
    "Calf Raise",
    "Hanging Leg Raise",
    "Ab Wheel",
    "Plank",
    "Cable Crunch",
    "Shrug",
    "Dips",
    "Push-Up",
    "Pec Deck",
    "Dumbbell Fly"
  ],
  "AGE_COEFFICIENTS": {
    "14": 1.23,
    "15": 1.18,
    "16": 1.13,
    "17": 1.08,
    "18": 1.06,
    "19": 1.04,
    "20": 1.03,
    "21": 1.02,
    "22": 1.01,
    "40": 1.0,
    "41": 1.01,
    "42": 1.02,
    "43": 1.031,
    "44": 1.043,
    "45": 1.055,
    "46": 1.068,
    "47": 1.082,
    "48": 1.097,
    "49": 1.113,
    "50": 1.13,
    "51": 1.147,
    "52": 1.165,
    "53": 1.184,
    "54": 1.204,
    "55": 1.225,
    "56": 1.246,
    "57": 1.268,
    "58": 1.291,
    "59": 1.315,
    "60": 1.34,
    "61": 1.366,
    "62": 1.393,
    "63": 1.421,
    "64": 1.45,
    "65": 1.48,
    "66": 1.511,
    "67": 1.543,
    "68": 1.576,
    "69": 1.61,
    "70": 1.645,
    "71": 1.681,
    "72": 1.718,
    "73": 1.756,
    "74": 1.795,
    "75": 1.835,
    "76": 1.876,
    "77": 1.918,
    "78": 1.961,
    "79": 2.005,
    "80": 2.05,
    "81": 2.096,
    "82": 2.143,
    "83": 2.19,
    "84": 2.238,
    "85": 2.287,
    "86": 2.337,
    "87": 2.388,
    "88": 2.44,
    "89": 2.494,
    "90": 2.549
  },
  "ALL_SLOTS": [
    "squat",
    "bench",
    "deadlift",
    "ohp",
    "squat_aux_1",
    "squat_aux_2",
    "bench_aux_1",
    "bench_aux_2",
    "deadlift_aux",
    "ohp_aux"
  ],
  "ALL_VARIANTS": [
    "rtf",
    "hypertrophy",
    "last_set_rir",
    "original"
  ],
  "ANDY_LOWER_DAY": [
    "Pull-Up",
    "Close Grip Pulldown",
    "Barbell Row",
    "Ab Wheel",
    "Hip Thrust"
  ],
  "ANDY_UPPER_DAY": [
    "Incline Bench Press",
    "Weighted Dips",
    "Lateral Raise",
    "Rear Delt Fly",
    "Cable Curl",
    "Hammer Curl",
    "Overhead Triceps Extension",
    "Triceps Pushdown",
    "Dumbbell Wrist Curl"
  ],
  "AUXILIARY_SLOTS": [
    "squat_aux_1",
    "squat_aux_2",
    "bench_aux_1",
    "bench_aux_2",
    "deadlift_aux",
    "ohp_aux"
  ],
  "BENCH_VARIATIONS": [
    "Bench Press",
    "Close Grip Bench",
    "Wide Grip Bench",
    "Incline Press",
    "Decline Bench",
    "Paused Bench",
    "Spoto Press",
    "Board Press",
    "Pin Press",
    "Floor Press",
    "Feet Up Bench",
    "Tempo Bench",
    "Slingshot Bench",
    "Dumbbell Bench",
    "Weighted Dips"
  ],
  "BODYWEIGHT_SCALING_EXPONENT": 0.667,
  "DEADLIFT_VARIATIONS": [
    "Deadlift",
    "Conventional Deadlift",
    "Sumo Deadlift",
    "Block Pull",
    "Rack Pull",
    "Deficit Deadlift",
    "Paused Deadlift",
    "Romanian Deadlift",
    "Stiff Leg Deadlift",
    "Snatch Grip Deadlift",
    "Trap Bar Deadlift"
  ],
  "DEFAULT_ROUNDING_INCREMENT": 2.5,
  "DEFAULT_SETS": {
    "original": 5,
    "last_set_rir": 5,
    "rtf": 5,
    "hypertrophy": 4
  },
  "DEFAULT_SINGLE_AT_8_PERCENT": 90.0,
  "DEFAULT_STARTING_MAXES": {
    "lb": {
      "squat": 225.0,
      "bench": 155.0,
      "deadlift": 275.0,
      "ohp": 95.0,
      "squat_aux_1": 185.0,
      "squat_aux_2": 205.0,
      "bench_aux_1": 145.0,
      "bench_aux_2": 135.0,
      "deadlift_aux": 255.0,
      "ohp_aux": 115.0
    },
    "kg": {
      "squat": 100.0,
      "bench": 70.0,
      "deadlift": 125.0,
      "ohp": 45.0,
      "squat_aux_1": 85.0,
      "squat_aux_2": 90.0,
      "bench_aux_1": 65.0,
      "bench_aux_2": 60.0,
      "deadlift_aux": 115.0,
      "ohp_aux": 52.5
    }
  },
  "DEFAULT_TM_LADDER": [
    -5.0,
    -2.0,
    0.0,
    0.5,
    1.0,
    1.5,
    2.0,
    3.0
  ],
  "DELOAD_REPS_PER_SET": 5,
  "DELOAD_WEEKS": [
    7,
    14,
    21
  ],
  "FREQUENCY_CHOICES": [
    2,
    3,
    4,
    5,
    6
  ],
  "HYPERTROPHY_AUXILIARY_OFFSET": 5.0,
  "HYPERTROPHY_DEFAULT_LIFT_NAMES": {
    "squat": "Squat",
    "bench": "Bench Press",
    "deadlift": "Block Pull",
    "ohp": "Overhead Press",
    "squat_aux_1": "Leg Press",
    "squat_aux_2": "Hack Squat",
    "bench_aux_1": "Incline Press",
    "bench_aux_2": "Dumbbell Bench",
    "deadlift_aux": "Romanian Deadlift",
    "ohp_aux": "Dumbbell OHP"
  },
  "HYPERTROPHY_LAST_SET_REP_TARGET": [
    25,
    23,
    21,
    19,
    18,
    16,
    15,
    13,
    12,
    11,
    10,
    9,
    8,
    6,
    5,
    4,
    3,
    2,
    2,
    1,
    1
  ],
  "HYPERTROPHY_MAIN_INTENSITIES": [
    70.0,
    72.5,
    75.0,
    72.5,
    75.0,
    77.5,
    60.0,
    72.5,
    75.0,
    77.5,
    75.0,
    77.5,
    80.0,
    60.0,
    75.0,
    77.5,
    80.0,
    77.5,
    80.0,
    82.5,
    60.0
  ],
  "HYPERTROPHY_REPS_PER_SET": [
    20,
    18,
    17,
    15,
    14,
    13,
    12,
    11,
    10,
    9,
    8,
    7,
    6,
    5,
    4,
    3,
    2,
    2,
    2,
    1,
    1
  ],
  "KG_PER_LB": 0.45359237,
  "LAST_SET_RIR_TARGET": [
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    3,
    2,
    2,
    2,
    2,
    1,
    1,
    1,
    1,
    1,
    0,
    0
  ],
  "LOWER_FREQUENCY_SPLITS": {
    "2": [
      [
        "squat",
        "bench",
        "deadlift_aux",
        "ohp_aux"
      ],
      [
        "deadlift",
        "ohp",
        "squat_aux_1",
        "bench_aux_1"
      ]
    ],
    "3": [
      [
        "squat",
        "deadlift",
        "squat_aux_1"
      ],
      [
        "bench",
        "ohp",
        "bench_aux_1"
      ],
      [
        "ohp_aux",
        "squat_aux_2",
        "bench_aux_2",
        "deadlift_aux"
      ]
    ],
    "4": [
      [
        "squat",
        "deadlift_aux",
        "squat_aux_2"
      ],
      [
        "bench",
        "ohp_aux",
        "bench_aux_2"
      ],
      [
        "deadlift",
        "squat_aux_1"
      ],
      [
        "ohp",
        "bench_aux_1"
      ]
    ],
    "5": [
      [
        "squat",
        "squat_aux_2"
      ],
      [
        "bench",
        "ohp_aux",
        "bench_aux_2"
      ],
      [
        "deadlift"
      ],
      [
        "ohp",
        "bench_aux_1"
      ],
      [
        "squat_aux_1",
        "deadlift_aux"
      ]
    ],
    "6": [
      [
        "squat",
        "squat_aux_2"
      ],
      [
        "bench",
        "bench_aux_1"
      ],
      [
        "deadlift"
      ],
      [
        "ohp"
      ],
      [
        "squat_aux_1",
        "deadlift_aux"
      ],
      [
        "bench_aux_2",
        "ohp_aux"
      ]
    ]
  },
  "MAIN_SLOTS": [
    "squat",
    "bench",
    "deadlift",
    "ohp"
  ],
  "OHP_VARIATIONS": [
    "Overhead Press",
    "Push Press",
    "Seated OHP",
    "Behind The Neck Press",
    "Z Press",
    "Incline Press",
    "Dumbbell OHP",
    "Log Press",
    "Axle Press",
    "Landmine Press"
  ],
  "ORIGINAL_DECREASE_PERCENT": -5.0,
  "ORIGINAL_INCREASE_PERCENT": 2.0,
  "ORIGINAL_LOWER_SET_THRESHOLD": 4,
  "ORIGINAL_RIR_CUTOFF": [
    5,
    5,
    5,
    5,
    4,
    4,
    4,
    4,
    3,
    3,
    3,
    3,
    2,
    2,
    2,
    2,
    1,
    1,
    1,
    0,
    0
  ],
  "ORIGINAL_UPPER_SET_THRESHOLD": 6,
  "PARENT_SLOT": {
    "squat_aux_1": "squat",
    "squat_aux_2": "squat",
    "bench_aux_1": "bench",
    "bench_aux_2": "bench",
    "deadlift_aux": "deadlift",
    "ohp_aux": "ohp"
  },
  "PERCENTAGE_BUCKETS": [
    50.0,
    52.5,
    55.0,
    57.5,
    60.0,
    62.5,
    65.0,
    67.5,
    70.0,
    72.5,
    75.0,
    77.5,
    80.0,
    82.5,
    85.0,
    87.5,
    90.0,
    92.5,
    95.0,
    97.5,
    100.0
  ],
  "PRESET_ANDY": "andys_routine",
  "PRESET_DESCRIPTIONS": {
    "sbs_defaults": "The templates as Stronger By Science ships them: four main lifts, six auxiliary variations, full-body days.",
    "andys_routine": "Six days, no overhead press, no variations. Squat and deadlift on Monday, Wednesday and Friday with back, core and hip work; bench on Tuesday, Thursday and Saturday with incline, dips, shoulders and arms."
  },
  "PRESET_KEYS": [
    "sbs_defaults",
    "andys_routine"
  ],
  "PRESET_NAMES": {
    "sbs_defaults": "SBS defaults",
    "andys_routine": "Andy's Routine"
  },
  "PRESET_SBS": "sbs_defaults",
  "RANK_TIERS": [
    {
      "key": "mortal",
      "name": "Mortal",
      "min_percentile": 0.0,
      "effect": "none"
    },
    {
      "key": "initiate",
      "name": "Initiate",
      "min_percentile": 5.0,
      "effect": "none"
    },
    {
      "key": "vanguard",
      "name": "Vanguard",
      "min_percentile": 12.5,
      "effect": "none"
    },
    {
      "key": "warden",
      "name": "Warden",
      "min_percentile": 20.0,
      "effect": "none"
    },
    {
      "key": "colossus",
      "name": "Colossus",
      "min_percentile": 35.0,
      "effect": "none"
    },
    {
      "key": "titan",
      "name": "Titan",
      "min_percentile": 50.0,
      "effect": "shine"
    },
    {
      "key": "atlas",
      "name": "Atlas",
      "min_percentile": 65.0,
      "effect": "shine"
    },
    {
      "key": "demigod",
      "name": "Demigod",
      "min_percentile": 80.0,
      "effect": "electric"
    },
    {
      "key": "transcendent",
      "name": "Transcendent",
      "min_percentile": 95.0,
      "effect": "electric"
    },
    {
      "key": "legend_1",
      "name": "Legend I",
      "min_percentile": 97.5,
      "effect": "aurora"
    },
    {
      "key": "legend_2",
      "name": "Legend II",
      "min_percentile": 98.75,
      "effect": "aurora"
    },
    {
      "key": "legend_3",
      "name": "Legend III",
      "min_percentile": 99.375,
      "effect": "aurora"
    }
  ],
  "RANK_TYPE_BY_SLOT": {
    "squat": "squat",
    "squat_aux_1": "squat",
    "squat_aux_2": "squat",
    "bench": "bench",
    "bench_aux_1": "bench",
    "bench_aux_2": "bench",
    "deadlift": "deadlift",
    "deadlift_aux": "deadlift",
    "ohp": "ohp",
    "ohp_aux": "ohp"
  },
  "RANK_TYPE_NAMES": {
    "squat": "squat",
    "bench": "bench press",
    "deadlift": "deadlift",
    "ohp": "overhead press"
  },
  "ROUNDING_CHOICES": [
    0.1,
    1.0,
    2.5,
    5.0
  ],
  "RTF_LAST_SET_REP_TARGET": [
    18,
    17,
    16,
    15,
    14,
    13,
    12,
    11,
    10,
    9,
    8,
    7,
    6,
    5,
    4,
    3,
    2,
    2,
    1,
    1,
    1
  ],
  "SETUP_PRESETS": {
    "andys_routine": {
      "variant": "rtf",
      "units": "lb",
      "rounding_increment": 5.0,
      "frequency": 6,
      "split_style": "upper_lower",
      "same_lifts": true,
      "skipped_slots": [
        "ohp",
        "ohp_aux"
      ],
      "lift_names": {
        "squat": "Squat",
        "bench": "Bench Press",
        "deadlift": "Sumo Deadlift",
        "ohp": "Overhead Press"
      },
      "days": {
        "squat": 1,
        "deadlift_aux": 1,
        "bench": 2,
        "squat_aux_1": 3,
        "bench_aux_1": 4,
        "deadlift": 5,
        "squat_aux_2": 5,
        "bench_aux_2": 6
      },
      "accessories": [
        [
          "Pull-Up",
          "Close Grip Pulldown",
          "Barbell Row",
          "Ab Wheel",
          "Hip Thrust"
        ],
        [
          "Incline Bench Press",
          "Weighted Dips",
          "Lateral Raise",
          "Rear Delt Fly",
          "Cable Curl",
          "Hammer Curl",
          "Overhead Triceps Extension",
          "Triceps Pushdown",
          "Dumbbell Wrist Curl"
        ],
        [
          "Romanian Deadlift",
          "Pull-Up",
          "Close Grip Pulldown",
          "Barbell Row",
          "Ab Wheel",
          "Hip Thrust"
        ],
        [
          "Incline Bench Press",
          "Weighted Dips",
          "Lateral Raise",
          "Rear Delt Fly",
          "Cable Curl",
          "Hammer Curl",
          "Overhead Triceps Extension",
          "Triceps Pushdown",
          "Dumbbell Wrist Curl"
        ],
        [
          "Pull-Up",
          "Close Grip Pulldown",
          "Barbell Row",
          "Ab Wheel",
          "Hip Thrust"
        ],
        [
          "Incline Bench Press",
          "Weighted Dips",
          "Lateral Raise",
          "Rear Delt Fly",
          "Cable Curl",
          "Hammer Curl",
          "Overhead Triceps Extension",
          "Triceps Pushdown",
          "Dumbbell Wrist Curl"
        ]
      ]
    }
  },
  "SEX_CHOICES": [
    "male",
    "female"
  ],
  "SEX_NAMES": {
    "male": "Male",
    "female": "Female"
  },
  "SHORT_SLOT_LABELS": {
    "squat": "main",
    "bench": "main",
    "deadlift": "main",
    "ohp": "main",
    "squat_aux_1": "aux 1",
    "squat_aux_2": "aux 2",
    "bench_aux_1": "aux 1",
    "bench_aux_2": "aux 2",
    "deadlift_aux": "aux",
    "ohp_aux": "aux"
  },
  "SLOT_LABELS": {
    "squat": "Squat (main)",
    "bench": "Bench (main)",
    "deadlift": "Deadlift (main)",
    "ohp": "Overhead press (main)",
    "squat_aux_1": "Squat auxiliary 1",
    "squat_aux_2": "Squat auxiliary 2",
    "bench_aux_1": "Bench auxiliary 1",
    "bench_aux_2": "Bench auxiliary 2",
    "deadlift_aux": "Deadlift auxiliary",
    "ohp_aux": "Overhead press auxiliary"
  },
  "SLOT_VARIATIONS": {
    "squat": [
      "Squat",
      "High Bar Squat",
      "Low Bar Squat",
      "Front Squat",
      "Paused Squat",
      "Box Squat",
      "Pin Squat",
      "Beltless Squat",
      "Safety Bar Squat",
      "Wide Stance Squat",
      "Narrow Stance Squat",
      "Tempo Squat",
      "Half Squat",
      "Good Morning",
      "Leg Press",
      "Hack Squat",
      "Bulgarian Split Squat",
      "Lunges",
      "Zercher Squat"
    ],
    "bench": [
      "Bench Press",
      "Close Grip Bench",
      "Wide Grip Bench",
      "Incline Press",
      "Decline Bench",
      "Paused Bench",
      "Spoto Press",
      "Board Press",
      "Pin Press",
      "Floor Press",
      "Feet Up Bench",
      "Tempo Bench",
      "Slingshot Bench",
      "Dumbbell Bench",
      "Weighted Dips"
    ],
    "deadlift": [
      "Deadlift",
      "Conventional Deadlift",
      "Sumo Deadlift",
      "Block Pull",
      "Rack Pull",
      "Deficit Deadlift",
      "Paused Deadlift",
      "Romanian Deadlift",
      "Stiff Leg Deadlift",
      "Snatch Grip Deadlift",
      "Trap Bar Deadlift"
    ],
    "ohp": [
      "Overhead Press",
      "Push Press",
      "Seated OHP",
      "Behind The Neck Press",
      "Z Press",
      "Incline Press",
      "Dumbbell OHP",
      "Log Press",
      "Axle Press",
      "Landmine Press"
    ],
    "squat_aux_1": [
      "Squat",
      "High Bar Squat",
      "Low Bar Squat",
      "Front Squat",
      "Paused Squat",
      "Box Squat",
      "Pin Squat",
      "Beltless Squat",
      "Safety Bar Squat",
      "Wide Stance Squat",
      "Narrow Stance Squat",
      "Tempo Squat",
      "Half Squat",
      "Good Morning",
      "Leg Press",
      "Hack Squat",
      "Bulgarian Split Squat",
      "Lunges",
      "Zercher Squat"
    ],
    "squat_aux_2": [
      "Squat",
      "High Bar Squat",
      "Low Bar Squat",
      "Front Squat",
      "Paused Squat",
      "Box Squat",
      "Pin Squat",
      "Beltless Squat",
      "Safety Bar Squat",
      "Wide Stance Squat",
      "Narrow Stance Squat",
      "Tempo Squat",
      "Half Squat",
      "Good Morning",
      "Leg Press",
      "Hack Squat",
      "Bulgarian Split Squat",
      "Lunges",
      "Zercher Squat"
    ],
    "bench_aux_1": [
      "Bench Press",
      "Close Grip Bench",
      "Wide Grip Bench",
      "Incline Press",
      "Decline Bench",
      "Paused Bench",
      "Spoto Press",
      "Board Press",
      "Pin Press",
      "Floor Press",
      "Feet Up Bench",
      "Tempo Bench",
      "Slingshot Bench",
      "Dumbbell Bench",
      "Weighted Dips"
    ],
    "bench_aux_2": [
      "Bench Press",
      "Close Grip Bench",
      "Wide Grip Bench",
      "Incline Press",
      "Decline Bench",
      "Paused Bench",
      "Spoto Press",
      "Board Press",
      "Pin Press",
      "Floor Press",
      "Feet Up Bench",
      "Tempo Bench",
      "Slingshot Bench",
      "Dumbbell Bench",
      "Weighted Dips"
    ],
    "deadlift_aux": [
      "Deadlift",
      "Conventional Deadlift",
      "Sumo Deadlift",
      "Block Pull",
      "Rack Pull",
      "Deficit Deadlift",
      "Paused Deadlift",
      "Romanian Deadlift",
      "Stiff Leg Deadlift",
      "Snatch Grip Deadlift",
      "Trap Bar Deadlift"
    ],
    "ohp_aux": [
      "Overhead Press",
      "Push Press",
      "Seated OHP",
      "Behind The Neck Press",
      "Z Press",
      "Incline Press",
      "Dumbbell OHP",
      "Log Press",
      "Axle Press",
      "Landmine Press"
    ]
  },
  "SPLITS_BY_STYLE": {
    "full_body": {
      "2": [
        [
          "squat",
          "bench",
          "deadlift_aux",
          "ohp_aux"
        ],
        [
          "deadlift",
          "ohp",
          "squat_aux_1",
          "bench_aux_1"
        ]
      ],
      "3": [
        [
          "squat",
          "deadlift_aux",
          "bench_aux_2"
        ],
        [
          "bench",
          "ohp",
          "squat_aux_1"
        ],
        [
          "deadlift",
          "bench_aux_1",
          "squat_aux_2",
          "ohp_aux"
        ]
      ],
      "4": [
        [
          "squat",
          "bench_aux_2",
          "deadlift_aux"
        ],
        [
          "bench",
          "squat_aux_1",
          "ohp_aux"
        ],
        [
          "deadlift",
          "bench_aux_1"
        ],
        [
          "ohp",
          "squat_aux_2"
        ]
      ],
      "5": [
        [
          "squat",
          "ohp_aux"
        ],
        [
          "bench",
          "squat_aux_1"
        ],
        [
          "deadlift",
          "bench_aux_1"
        ],
        [
          "ohp",
          "squat_aux_2"
        ],
        [
          "bench_aux_2",
          "deadlift_aux"
        ]
      ],
      "6": [
        [
          "squat",
          "bench_aux_1"
        ],
        [
          "ohp_aux",
          "deadlift_aux"
        ],
        [
          "bench",
          "squat_aux_1"
        ],
        [
          "bench_aux_2",
          "squat_aux_2"
        ],
        [
          "deadlift"
        ],
        [
          "ohp"
        ]
      ]
    },
    "upper_lower": {
      "2": [
        [
          "squat",
          "bench",
          "deadlift_aux",
          "ohp_aux"
        ],
        [
          "deadlift",
          "ohp",
          "squat_aux_1",
          "bench_aux_1"
        ]
      ],
      "3": [
        [
          "squat",
          "deadlift",
          "squat_aux_1"
        ],
        [
          "bench",
          "ohp",
          "bench_aux_1"
        ],
        [
          "ohp_aux",
          "squat_aux_2",
          "bench_aux_2",
          "deadlift_aux"
        ]
      ],
      "4": [
        [
          "squat",
          "deadlift_aux",
          "squat_aux_2"
        ],
        [
          "bench",
          "ohp_aux",
          "bench_aux_2"
        ],
        [
          "deadlift",
          "squat_aux_1"
        ],
        [
          "ohp",
          "bench_aux_1"
        ]
      ],
      "5": [
        [
          "squat",
          "squat_aux_2"
        ],
        [
          "bench",
          "ohp_aux",
          "bench_aux_2"
        ],
        [
          "deadlift"
        ],
        [
          "ohp",
          "bench_aux_1"
        ],
        [
          "squat_aux_1",
          "deadlift_aux"
        ]
      ],
      "6": [
        [
          "squat",
          "squat_aux_2"
        ],
        [
          "bench",
          "bench_aux_1"
        ],
        [
          "deadlift"
        ],
        [
          "ohp"
        ],
        [
          "squat_aux_1",
          "deadlift_aux"
        ],
        [
          "bench_aux_2",
          "ohp_aux"
        ]
      ]
    }
  },
  "SPLIT_FULL_BODY": "full_body",
  "SPLIT_STYLES": [
    "full_body",
    "upper_lower"
  ],
  "SPLIT_STYLE_DESCRIPTIONS": {
    "full_body": "Each movement pattern two or three times a week, often on back-to-back days, with the extra exposures 10 points lighter.",
    "upper_lower": "Lower-body and upper-body days alternate, so squats never follow squats. Same lifts and same numbers, just grouped differently."
  },
  "SPLIT_STYLE_NAMES": {
    "full_body": "Full body (SBS default)",
    "upper_lower": "Upper / lower (SBS lower-frequency templates)"
  },
  "SPLIT_UPPER_LOWER": "upper_lower",
  "SQUAT_VARIATIONS": [
    "Squat",
    "High Bar Squat",
    "Low Bar Squat",
    "Front Squat",
    "Paused Squat",
    "Box Squat",
    "Pin Squat",
    "Beltless Squat",
    "Safety Bar Squat",
    "Wide Stance Squat",
    "Narrow Stance Squat",
    "Tempo Squat",
    "Half Squat",
    "Good Morning",
    "Leg Press",
    "Hack Squat",
    "Bulgarian Split Squat",
    "Lunges",
    "Zercher Squat"
  ],
  "STANDARDS_REFERENCE_BODYWEIGHT_LB": {
    "male": 180.0,
    "female": 140.0
  },
  "STANDARD_PERCENTILES": [
    5.0,
    20.0,
    50.0,
    80.0,
    95.0
  ],
  "STANDARD_RATIOS": {
    "male": {
      "squat": [
        0.75,
        1.25,
        1.5,
        2.0,
        2.5
      ],
      "bench": [
        0.5,
        0.75,
        1.0,
        1.35,
        1.7
      ],
      "deadlift": [
        0.9,
        1.3,
        1.8,
        2.3,
        2.8
      ],
      "ohp": [
        0.4,
        0.55,
        0.75,
        1.0,
        1.2
      ]
    },
    "female": {
      "squat": [
        0.45,
        0.7,
        1.05,
        1.45,
        1.9
      ],
      "bench": [
        0.32,
        0.47,
        0.68,
        0.93,
        1.2
      ],
      "deadlift": [
        0.6,
        0.9,
        1.25,
        1.7,
        2.15
      ],
      "ohp": [
        0.22,
        0.32,
        0.47,
        0.65,
        0.82
      ]
    }
  },
  "STRENGTH_AUXILIARY_OFFSET": 10.0,
  "STRENGTH_DEFAULT_LIFT_NAMES": {
    "squat": "Squat",
    "bench": "Bench Press",
    "deadlift": "Deadlift",
    "ohp": "Overhead Press",
    "squat_aux_1": "Front Squat",
    "squat_aux_2": "Paused Squat",
    "bench_aux_1": "Close Grip Bench",
    "bench_aux_2": "Incline Press",
    "deadlift_aux": "Sumo Deadlift",
    "ohp_aux": "Push Press"
  },
  "STRENGTH_MAIN_INTENSITIES": [
    70.0,
    75.0,
    80.0,
    72.5,
    77.5,
    82.5,
    60.0,
    75.0,
    80.0,
    85.0,
    77.5,
    82.5,
    87.5,
    60.0,
    80.0,
    85.0,
    90.0,
    85.0,
    90.0,
    95.0,
    60.0
  ],
  "STRENGTH_REPS_PER_SET": [
    8,
    8,
    8,
    8,
    7,
    7,
    6,
    6,
    5,
    5,
    4,
    4,
    3,
    3,
    2,
    2,
    1,
    1,
    1,
    1,
    1
  ],
  "STRENGTH_VARIANTS": [
    "original",
    "last_set_rir",
    "rtf"
  ],
  "TM_LADDER_LABELS": [
    "2+ below target",
    "1 below target",
    "Hit target",
    "Beat by 1",
    "Beat by 2",
    "Beat by 3",
    "Beat by 4",
    "Beat by 5+"
  ],
  "TOTAL_WEEKS": 21,
  "TRAINING_SPLITS": {
    "2": [
      [
        "squat",
        "bench",
        "deadlift_aux",
        "ohp_aux"
      ],
      [
        "deadlift",
        "ohp",
        "squat_aux_1",
        "bench_aux_1"
      ]
    ],
    "3": [
      [
        "squat",
        "deadlift_aux",
        "bench_aux_2"
      ],
      [
        "bench",
        "ohp",
        "squat_aux_1"
      ],
      [
        "deadlift",
        "bench_aux_1",
        "squat_aux_2",
        "ohp_aux"
      ]
    ],
    "4": [
      [
        "squat",
        "bench_aux_2",
        "deadlift_aux"
      ],
      [
        "bench",
        "squat_aux_1",
        "ohp_aux"
      ],
      [
        "deadlift",
        "bench_aux_1"
      ],
      [
        "ohp",
        "squat_aux_2"
      ]
    ],
    "5": [
      [
        "squat",
        "ohp_aux"
      ],
      [
        "bench",
        "squat_aux_1"
      ],
      [
        "deadlift",
        "bench_aux_1"
      ],
      [
        "ohp",
        "squat_aux_2"
      ],
      [
        "bench_aux_2",
        "deadlift_aux"
      ]
    ],
    "6": [
      [
        "squat",
        "bench_aux_1"
      ],
      [
        "ohp_aux",
        "deadlift_aux"
      ],
      [
        "bench",
        "squat_aux_1"
      ],
      [
        "bench_aux_2",
        "squat_aux_2"
      ],
      [
        "deadlift"
      ],
      [
        "ohp"
      ]
    ]
  },
  "UNIT_CHOICES": [
    "lb",
    "kg"
  ],
  "UPPER_BACK_EXERCISES": [
    "Barbell Row",
    "Dumbbell Row",
    "Chest Supported Row",
    "T-Bar Row",
    "Pull-Up",
    "Chin-Up",
    "Neutral Grip Pull-Up",
    "Lat Pulldown",
    "Seated Cable Row"
  ],
  "VARIANT_DESCRIPTIONS": {
    "original": "Open-ended sets. Keep doing sets of the prescribed reps until you reach the RIR (reps in reserve) cutoff, then log how many sets you finished. Too few sets lowers your training max, extra sets raise it.",
    "last_set_rir": "Fixed number of sets (5 by default). After the final set you rate how many reps you had left in the tank. More reps in reserve than the target raises your training max; fewer lowers it.",
    "rtf": "Fixed number of sets (5 by default): the first four at the prescribed reps, the last one for as many reps as possible. Beat the last-set rep target and your training max goes up; fall short and it comes down.",
    "hypertrophy": "Same idea as Reps to Failure but with 4 sets (3 normal + 1 to failure), higher reps, and a lower intensity ceiling of 82.5%. Aimed at muscle growth."
  },
  "VARIANT_HYPERTROPHY": "hypertrophy",
  "VARIANT_LAST_SET_RIR": "last_set_rir",
  "VARIANT_NAMES": {
    "original": "SBS Strength Program (Original)",
    "last_set_rir": "SBS Strength Program - Last Set RIR",
    "rtf": "SBS Strength Program - Reps to Failure (RTF)",
    "hypertrophy": "SBS Hypertrophy Template"
  },
  "VARIANT_ORIGINAL": "original",
  "VARIANT_RTF": "rtf",
  "VARIATION_RANK_FACTORS": {
    "front squat": 0.85,
    "paused squat": 0.9,
    "pause squat": 0.9,
    "high bar squat": 0.95,
    "low bar squat": 1.0,
    "box squat": 0.95,
    "pin squat": 0.9,
    "beltless squat": 0.95,
    "safety bar squat": 0.9,
    "tempo squat": 0.9,
    "half squat": 1.2,
    "leg press": 2.0,
    "hack squat": 1.3,
    "bulgarian split squat": 0.5,
    "lunges": 0.5,
    "zercher squat": 0.8,
    "goblet squat": 0.4,
    "good morning": 0.5,
    "close grip bench": 0.9,
    "wide grip bench": 1.0,
    "incline press": 0.8,
    "incline bench press": 0.8,
    "decline bench": 1.05,
    "paused bench": 0.95,
    "spoto press": 0.95,
    "board press": 1.05,
    "pin press": 0.95,
    "floor press": 0.95,
    "feet up bench": 0.9,
    "tempo bench": 0.9,
    "slingshot bench": 1.1,
    "dumbbell bench": 0.75,
    "weighted dips": 1.0,
    "sumo deadlift": 1.0,
    "conventional deadlift": 1.0,
    "block pull": 1.1,
    "rack pull": 1.2,
    "deficit deadlift": 0.9,
    "paused deadlift": 0.9,
    "romanian deadlift": 0.85,
    "stiff leg deadlift": 0.8,
    "snatch grip deadlift": 0.85,
    "trap bar deadlift": 1.1,
    "push press": 1.2,
    "seated ohp": 0.95,
    "behind the neck press": 0.85,
    "z press": 0.8,
    "dumbbell ohp": 0.7,
    "log press": 0.9,
    "axle press": 0.95,
    "landmine press": 0.6
  },
  "WEEKS_PER_BLOCK": 7
};
const IMAGE_OVERRIDES = {
  "squat": "Barbell_Squat",
  "back squat": "Barbell_Squat",
  "high bar squat": "Barbell_Full_Squat",
  "low bar squat": "Barbell_Squat",
  "front squat": "Front_Barbell_Squat",
  "paused squat": "Barbell_Full_Squat",
  "pause squat": "Barbell_Full_Squat",
  "box squat": "Box_Squat",
  "pin squat": "Barbell_Squat",
  "beltless squat": "Barbell_Squat",
  "safety bar squat": "Barbell_Squat",
  "ssb squat": "Barbell_Squat",
  "wide stance squat": "Wide_Stance_Barbell_Squat",
  "wider stance squat": "Wide_Stance_Barbell_Squat",
  "narrow stance squat": "Narrow_Stance_Squats",
  "narrower stance squat": "Narrow_Stance_Squats",
  "tempo squat": "Barbell_Squat",
  "squat with slow eccentric": "Barbell_Squat",
  "half squat": "Barbell_Squat",
  "good morning": "Good_Morning",
  "leg press": "Leg_Press",
  "hack squat": "Hack_Squat",
  "bulgarian split squat": "Split_Squat_with_Dumbbells",
  "lunges": "Barbell_Lunge",
  "lunge": "Barbell_Lunge",
  "zercher squat": "Zercher_Squats",
  "goblet squat": "Goblet_Squat",
  "bench press": "Barbell_Bench_Press_-_Medium_Grip",
  "bench": "Barbell_Bench_Press_-_Medium_Grip",
  "competition bench": "Barbell_Bench_Press_-_Medium_Grip",
  "close grip bench": "Close-Grip_Barbell_Bench_Press",
  "close grip bench press": "Close-Grip_Barbell_Bench_Press",
  "wide grip bench": "Wide-Grip_Barbell_Bench_Press",
  "wider grip bench": "Wide-Grip_Barbell_Bench_Press",
  "incline press": "Barbell_Incline_Bench_Press_-_Medium_Grip",
  "incline bench": "Barbell_Incline_Bench_Press_-_Medium_Grip",
  "incline bench press": "Barbell_Incline_Bench_Press_-_Medium_Grip",
  "decline bench": "Decline_Barbell_Bench_Press",
  "paused bench": "Barbell_Bench_Press_-_Medium_Grip",
  "long pause bench": "Barbell_Bench_Press_-_Medium_Grip",
  "spoto press": "Barbell_Bench_Press_-_Medium_Grip",
  "board press": "Board_Press",
  "pin press": "Pin_Presses",
  "floor press": "Floor_Press",
  "feet up bench": "Barbell_Bench_Press_-_Medium_Grip",
  "bench with feet up": "Barbell_Bench_Press_-_Medium_Grip",
  "tempo bench": "Barbell_Bench_Press_-_Medium_Grip",
  "bench with slow eccentric": "Barbell_Bench_Press_-_Medium_Grip",
  "slingshot bench": "Bench_Press_-_With_Bands",
  "dumbbell bench": "Dumbbell_Bench_Press",
  "db bench": "Dumbbell_Bench_Press",
  "dumbbell bench press": "Dumbbell_Bench_Press",
  "weighted dips": "Dips_-_Chest_Version",
  "dips": "Dips_-_Triceps_Version",
  "deadlift": "Barbell_Deadlift",
  "conventional deadlift": "Barbell_Deadlift",
  "sumo deadlift": "Sumo_Deadlift",
  "block pull": "Rack_Pulls",
  "block pulls": "Rack_Pulls",
  "rack pull": "Rack_Pulls",
  "rack pulls": "Rack_Pulls",
  "deficit deadlift": "Deficit_Deadlift",
  "paused deadlift": "Barbell_Deadlift",
  "romanian deadlift": "Romanian_Deadlift",
  "rdl": "Romanian_Deadlift",
  "stiff leg deadlift": "Stiff-Legged_Barbell_Deadlift",
  "stiff legged deadlift": "Stiff-Legged_Barbell_Deadlift",
  "snatch grip deadlift": "Snatch_Deadlift",
  "trap bar deadlift": "Trap_Bar_Deadlift",
  "overhead press": "Standing_Military_Press",
  "ohp": "Standing_Military_Press",
  "military press": "Standing_Military_Press",
  "press": "Standing_Military_Press",
  "strict press": "Standing_Military_Press",
  "push press": "Push_Press",
  "seated ohp": "Seated_Barbell_Military_Press",
  "seated press": "Seated_Barbell_Military_Press",
  "behind the neck press": "Standing_Barbell_Press_Behind_Neck",
  "behind the neck ohp": "Standing_Barbell_Press_Behind_Neck",
  "z press": "Seated_Barbell_Military_Press",
  "dumbbell ohp": "Dumbbell_Shoulder_Press",
  "db ohp": "Dumbbell_Shoulder_Press",
  "dumbbell shoulder press": "Dumbbell_Shoulder_Press",
  "log press": "Log_Lift",
  "axle press": "Standing_Military_Press",
  "landmine press": "Standing_Military_Press",
  "barbell row": "Bent_Over_Barbell_Row",
  "barbell rows": "Bent_Over_Barbell_Row",
  "bent over row": "Bent_Over_Barbell_Row",
  "pendlay row": "Bent_Over_Barbell_Row",
  "dumbbell row": "One-Arm_Dumbbell_Row",
  "db row": "One-Arm_Dumbbell_Row",
  "db rows": "One-Arm_Dumbbell_Row",
  "chest supported row": "Dumbbell_Incline_Row",
  "chest supported rows": "Dumbbell_Incline_Row",
  "t bar row": "T-Bar_Row_with_Handle",
  "t bar rows": "T-Bar_Row_with_Handle",
  "pull up": "Pullups",
  "pull ups": "Pullups",
  "pullup": "Pullups",
  "pullups": "Pullups",
  "weighted pull up": "Pullups",
  "chin up": "Chin-Up",
  "chin ups": "Chin-Up",
  "chinup": "Chin-Up",
  "neutral grip pull up": "V-Bar_Pullup",
  "neutral grip pull ups": "V-Bar_Pullup",
  "lat pulldown": "Wide-Grip_Lat_Pulldown",
  "close grip pulldown": "Close-Grip_Front_Lat_Pulldown",
  "close grip pulldowns": "Close-Grip_Front_Lat_Pulldown",
  "pulldown": "Wide-Grip_Lat_Pulldown",
  "pull downs": "Wide-Grip_Lat_Pulldown",
  "pulldowns": "Wide-Grip_Lat_Pulldown",
  "seated cable row": "Seated_Cable_Rows",
  "cable row": "Seated_Cable_Rows",
  "face pull": "Face_Pull",
  "lateral raise": "Side_Lateral_Raise",
  "side raise": "Side_Lateral_Raise",
  "rear delt fly": "Seated_Bent-Over_Rear_Delt_Raise",
  "rear delt raise": "Seated_Bent-Over_Rear_Delt_Raise",
  "barbell curl": "Barbell_Curl",
  "dumbbell curl": "Dumbbell_Bicep_Curl",
  "cable curl": "Standing_Biceps_Cable_Curl",
  "bicep cable curl": "Standing_Biceps_Cable_Curl",
  "dumbbell wrist curl": "Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench",
  "wrist curl": "Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench",
  "hammer curl": "Hammer_Curls",
  "triceps pushdown": "Triceps_Pushdown",
  "tricep pushdown": "Triceps_Pushdown",
  "skull crusher": "Lying_Triceps_Press",
  "skullcrusher": "Lying_Triceps_Press",
  "overhead triceps extension": "Standing_Overhead_Barbell_Triceps_Extension",
  "leg curl": "Lying_Leg_Curls",
  "leg extension": "Leg_Extensions",
  "hip thrust": "Barbell_Hip_Thrust",
  "back extension": "Hyperextensions_Back_Extensions",
  "glute ham raise": "Glute_Ham_Raise",
  "calf raise": "Standing_Calf_Raises",
  "hanging leg raise": "Hanging_Leg_Raise",
  "ab wheel": "Ab_Roller",
  "plank": "Plank",
  "cable crunch": "Cable_Crunch",
  "shrug": "Barbell_Shrug",
  "push up": "Pushups",
  "pushup": "Pushups",
  "pec deck": "Butterfly",
  "dumbbell fly": "Dumbbell_Flyes"
};
if (typeof module !== "undefined") {
  module.exports = { DEFAULTS: DEFAULTS, IMAGE_OVERRIDES: IMAGE_OVERRIDES };
} else {
  window.SBS_DEFAULTS = DEFAULTS;
  window.SBS_IMAGE_OVERRIDES = IMAGE_OVERRIDES;
}
